#!/usr/bin/env bash
# Generates a compressed archive of a MySQL dump.
# mysqldump -uroot -p"$1" --all-databases > backup.sql
# tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql

day=$(date +"%d")
month=$(date +%m")
year=$(date +"%Y")
filename="$day-$month-$year.tar.gz"

mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$filename" backup.sql