#!/usr/bin/env bash
#Displays the content of the file /etc/passwd
while read -r line
do
	username=$(echo "$line" | cut -d ':' -f 1)
	userid=$(echo "$line" | cut -d ':' -f 3)
	home_dir=$(echo "$line" | cut -d ':' -f 6)
	echo "$username:$userid:$home_dir"
done < /etc/passwd
