#!/usr/bin/env bash
# Configures an Ubuntu server with the below requirements:
# localhost resolves to 127.0.0.1
# facebook.com resolves to 8.8.8.8
echo "localhost 127.0.0.2" >> /etc/hosts
echo "facebook.com 8.8.8.8" >> /etc/hosts
