#!/usr/bin/env bash
# Configures an Ubuntu server with the below requirements:
# localhost resolves to 127.0.0.1
# facebook.com resolves to 8.8.8.8
echo "127.0.0.2\tlocalhost" >> /etc/hosts
echo "8.8.8.8\tfacebook.com" >> /etc/hosts
